# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INC_IMPACT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impactlabel', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='INC_REMEDIAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('action_owner', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=12)),
                ('date_raised', models.DateTimeField(verbose_name='date raised')),
            ],
        ),
        migrations.CreateModel(
            name='INC_REPORTED_METHOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodlabel', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='INC_RESPONSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='INC_ROOT_CAUSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='INC_SEVERITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('value', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='INC_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inctypelabel', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='INCIDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incref', models.CharField(max_length=9)),
                ('date_reported', models.DateTimeField(verbose_name='reported on')),
                ('date_happened', models.DateTimeField(verbose_name='happened on')),
                ('reported_by', models.CharField(max_length=100)),
                ('incident_summary_headline', models.CharField(max_length=100)),
                ('incident_recovery_time', models.IntegerField(null=True)),
                ('linked_risk_ref', models.CharField(max_length=30)),
                ('incident_impact', models.ManyToManyField(to='incidents.INC_IMPACT')),
                ('incident_remedial_actions', models.ManyToManyField(to='incidents.INC_REMEDIAL')),
                ('incident_response_actions', models.ManyToManyField(to='incidents.INC_RESPONSE')),
                ('incident_root_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.INC_ROOT_CAUSE')),
                ('incident_severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.INC_SEVERITY')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.INC_TYPE')),
                ('reported_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.INC_REPORTED_METHOD')),
            ],
        ),
    ]
