# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc_severity',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='inc_type',
            name='inctypelabel',
            field=models.CharField(default='', max_length=40),
        ),
    ]
