# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20160720_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc_severity',
            name='description',
            field=models.CharField(max_length=90),
        ),
    ]
