# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20160720_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_detail',
            field=models.TextField(blank=True),
        ),
    ]
